In [31]:
import pandas as pd

In [34]:
file_path = r"C:\Users\G_BOOTS\OneDrive\Desktop\heritage flowers\HERITAGE VARIETIES DAILY PRODUCTION RECORD.xlsx"

xls = pd.ExcelFile(file_path)

print(xls.sheet_names)

['JANUARY 2026', 'FEBRUARY 2026', 'MARCH 2026', 'Sheet1']

In [56]:
df_jan = pd.read_excel(xls, sheet_name="JANUARY 2026")
df_feb = pd.read_excel(xls, sheet_name="FEBRUARY 2026")
df_mar = pd.read_excel(xls, sheet_name="MARCH 2026")

In [ ]:
# Print all
print(df_jan)
print(df_feb)
print(df_mar)

In [58]:
df_all = pd.concat([df_jan, df_feb, df_mar])

In [59]:
# STANDARD ROSES
standard_roses = [
    "MADAM RED","NIGHT GALE","ATHENA WHITE","ROYAL ATHENA","PINK ATHENA",
    "EVERED","REDBENTLY","BELLA ROSE","CARISE","ORANGE WAVE","MOONWALK",
    "MOVIE STAR","BAHAMA","CELINA","LABELLE","LAMPION","JUMILIA","CHELSIE",
    "DESERT QUEEN","REVIVAL","MADAM CERISE","MADAM PINK","PURPLE BLISS",
    "RED WAVE","PINK SWIRL","BALTTORE","THRILLER","MAITAI","TIGER","PIXIE","TRIALS"
]

# SPRAY ROSES
spray_roses = [
    "WEDDING PARTY","ODILIA","SNW BUBBLE","SOWFLAKE","COLLEEN","SALINERO",
    "QUINCY","SNOW BLOSSOM","OLYMPIA","PUSKIN","ZADIQUE","PICANTO",
    "GOOD MOOD","SMOOTH.BLOSSOMS","YELLOW BABE","ROYAL MAGIC","FANCY",
    "MIRABELL","RTS","US","AZORE","VELOX","VELVET","GOLDEN BLOSSOM",
    "RELANX","INNOCENT","TARANTELLA","SWEET BLOSSOM","S.SHADOW","MARISSA",
    "B.BUBBLE","PASSION","EARTH AND FIRE","FIREWORK","LAND AND FIRE",
    "SEDINA","REFLEX","NIKITA","SPEAKING BLOSSOM"
]

In [1]:
def get_category(variety):
    variety = variety.upper().strip()
    
    if variety in standard_roses:
        return "Standard Roses"
    elif variety in spray_roses:
        return "Spray Roses"
    else:
        return "Unknown"

In [61]:
clean_data = []

for sheet in xls.sheet_names:
    
    # Skip unwanted sheet
    if "VARIETY SALES REPORT MARCH" in sheet.upper():
        continue

    df = xls.parse(sheet)
    df = df.dropna(how='all').reset_index(drop=True)

    for i in range(len(df)):
        row = df.iloc[i]
        variety = str(row.iloc[0]).strip().upper()

        # Skip invalid rows
        if variety == "NAN" or "TOTAL" in variety or "ROSES" in variety:
            continue

        category = get_category(variety)

        # Loop through date columns
        for col in df.columns[1:]:
            value = row[col]

            if pd.isna(value):
                continue

            try:
                date = pd.to_datetime(col)
            except:
                continue

            clean_data.append({
                "Date": date,
                "Variety": variety,
                "Category": category,
                "Production_Qty": value
            })

In [ ]:
clean_df = pd.DataFrame(clean_data)

clean_df.head()

        Date     Variety        Category  Production_Qty
0 2026-03-01   MADAM RED  Standard Roses            5255
1 2026-03-02   MADAM RED  Standard Roses            3665
2 2026-03-03   MADAM RED  Standard Roses            3458
3 2026-03-04   MADAM RED  Standard Roses            4364
4 2026-03-01  NIGHT GALE  Standard Roses             620

In [41]:
print(clean_df['Category'].value_counts())

# Check unknowns
unknowns = clean_df[clean_df['Category'] == 'Unknown']['Variety'].unique()
print("Unknown varieties:", unknowns)

Category
Spray Roses       156
Standard Roses    124
Name: count, dtype: int64
Unknown varieties: []

In [46]:
clean_df.head(150)

          Date     Variety        Category  Production_Qty
0   2026-03-01   MADAM RED  Standard Roses            5255
1   2026-03-02   MADAM RED  Standard Roses            3665
2   2026-03-03   MADAM RED  Standard Roses            3458
3   2026-03-04   MADAM RED  Standard Roses            4364
4   2026-03-01  NIGHT GALE  Standard Roses             620
..         ...         ...             ...             ...
145 2026-03-02    SALINERO     Spray Roses             260
146 2026-03-03    SALINERO     Spray Roses             336
147 2026-03-04    SALINERO     Spray Roses             352
148 2026-03-01      QUINCY     Spray Roses              70
149 2026-03-02      QUINCY     Spray Roses             100

[150 rows x 4 columns]

In [47]:
output_path = r"C:\Users\G_BOOTS\OneDrive\Desktop\heritage flowers\clean_production_data.xlsx"

clean_df.to_excel(output_path, index=False)

print("✅ Clean production data saved successfully!")

✅ Clean production data saved successfully!